[package]
name = "manager"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
json = "0.12.4"
log = "0.4.22"
serde = "1.0.216"
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["full"] }
